var questions = [
  "Worin besteht das Problem?",
  "Wann tritt das Problem auf?",
  "Welche Ressourcen habe ich momentan zur Verfügung um das Problem zu lösen?",
  "Welche Menschen können mir dabei helfen, das Problem zu lösen?",
  "Wann habe ich das letzte Mal intensiv über dieses Problem nachgedacht?",
  "Auf welche Ressourcen würden mich andere hinweisen?",
  "Was würde ich mir raten, wenn ich Berater wär?",
  "Was müsste ich tun, um eine Lösung des Problems zu verhindern?",
  "Wer konnte mir bei meinem letzten Problem helfen?",
  "Welchen Nutzen habe ich von dem Problem?",
  "Was wäre der nächste Schritt, den ich gehen könnte, um das Problem zu lösen?",
  "Wie würde es sein, wenn das Problem gelöst wäre?",
  "Für wen würde sich etwas ändern, wenn das Problem gelöst wäre?",
  "Wer ist alles von dem Problem betroffen?",
  "Was würde passieren, wenn ich das Problem nicht angehen würde?",
  "Wann habe ich mich das letzte Mal bei einem Menschen für etwas bedankt?",
  "Wann war ich das letzte Mal an der frischen Luft unterwegs?",
  "Welche Frage stelle ich mir eigentlich gerade?",
  "Wie schlimm ist mein altuelles Problem?",
  "Was treibt mich an?",
  "Warum bin ich auf dieser Seite?",
  "Unter welchen Bedingungen kann ich am besten über etwas nachdenken?",
  "Was würde mir ein Kollege jetzt raten?",
  "Welcher Lösungsansatz hat sich bei dem letzten Problem bewährt?"
]
