var questions = [
  "Worin besteht das Problem?",
  "Wann tritt das Problem auf?",
  "Welche Ressourcen habe ich momentan zur Verfügung um das Problem zu lösen?",
  "Welche Menschen können mir dabei helfen, das Problem zu lösen?",
  "Wann habe ich das letzte Mal intensiv über dieses Problem nachgedacht?",
  "Auf welche Ressourcen würden mich andere hinweisen?",
  "Was würde ich mir raten, wenn ich Berater wär?",
  "Was müsste ich tun, um eine Lösung des Problems zu verhindern?",
  "Wer konnte mir bei meinem letzten Problem helfen?",
  "Welchen Nutzen habe ich von dem Problem?",
  "Was wäre der nächste Schritt, den ich gehen könnte, um das Problem zu lösen?",
  "Wie würde es sein, wenn das Problem gelöst wäre?",
  "Für wen würde sich etwas ändern, wenn das Problem gelöst wäre?",
  "Wer ist alles von dem Problem betroffen?",
  "Was würde passieren, wenn ich das Problem nicht angehen würde?",
  "Wann habe ich mich das letzte Mal bei einem Menschen für etwas bedankt?",
  "Wann war ich das letzte Mal an der frischen Luft unterwegs?",
  "Welche Frage stelle ich mir eigentlich gerade?",
  "Wie schlimm ist mein altuelles Problem?",
  "Was treibt mich an?",
  "Warum bin ich auf dieser Seite?",
  "Unter welchen Bedingungen kann ich am besten über etwas nachdenken?",
  "Was würde mir ein Kollege jetzt raten?",
  "Welcher Lösungsansatz hat sich bei dem letzten Problem bewährt?",
  "In welchem Augenblick ist mein Problem entstanden?",
  "Wen könnte ich um Rat bitten?",
  "Warum ist das Problem da?",
  "Bin ich am richtigen Problem dran oder nur an einem Symptom?",
  "Kenne ich das Spielfeld gut, in dem ich mich befinde?",
  "Für welches Problem suche ich gerade nach einer Lösung?",
  "Bin ich auf dem richtigen Weg?",
  "Was muss ich mir noch aneigenen, um mein Problem zu lösen?",
  "Sage ich zu oft \"Ich versuche ...\" anstatt zu sagen: \"Ich werde ...\"?",
  "Übernehme ich die Verantwortung für mein Handeln und Nichthandeln?",
  "Bin ich ausgeschlafen genug für das, was ich mir vornehme?",
  "Bin ich bei der Sache?",
  "Bin ich konzentriert?",
  "Welches Risiko bin ich bereit einzugehen?",
  "Welche längerfristigen Folgen hat mein Tun?",
  "Was tue ich am liebsten?",
  "Passt meine aktuelle Aufgabe zu meiner eigenen Lebensvision?",
  "Was muss zunächst abgeschlossen oder erledigt werden?",
  "Habe ich noch offene Kommunikation?",
  "Was hilft mir neue Sichtweisen zu entwickeln?",
  "Welchen Beitrag könnte ich jetzt dringend gebrauchen? Wie komme ich daran?",
  "Was brauche ich?",
  "Was hindert mich gerade?",
  "Auf was könnte ich am leichtesten verzichten?",
  "Woran erkenne ich, dass ich mein Problem gelöst habe?",
  "Was passiert, wenn ich einfach abwarte und nichts tue?",
  "Wie kann ich meine Ergebnisse messen?",
  "Wer kontrolliert, ob ich meine Arbeit gut mache?",
  "Was gibt mir Rückmeldung?",
  "Wie engagiert bin ich?",
  "Wie kann ich nach der Lösung verhindern, dass das Problem erneut auftritt?",
  "Wer weiß von dem Problem?",
  "Weiß ich alles über mein Problem?",
  "Weiß ich genug über mein Problem, um es lösen zu können?",
  "Wie kann ich mein Verhalten ändern, dass sich das Problem von selbst löst?",
  "Ist das Problem an dem ich arbeite auch mein Problem?",
  "Wessen Problem löse ich gerade?",
  "Welche Fragen habe ich mir noch nicht gestellt?",
  "Bin ich ehrlich zu mir?",
  "Löse ich gerade das wichtigste Problem?",
  "Was tue ich, wenn das Problem gelöst ist?",
  "Kann ich meine Fortschritte messen?",
  "Wann werde ich auf diese Seite das nächste mal zurückkehren?",
  "Wie wichtig ist eine gute Frage für mich?",
  "Wie lange dauert es, bis mein Handeln Wirkung zeigt?",
  "Was ist mein Ziel?",
  "Worauf will ich hinaus?",
  "Was verändert sich in meiner Umgebung, wenn ich fertig bin?",
  "Habe ich bereits begonnen?",
  "Wann werde ich beginnen?",
  "An welchem Ort erziele ich die besten Ergebnisse?",
  "Werde ich serenize.me weiterempfehlen?",
  "Wie überzeuge ich andere Mitsteiter für mein Problem?",
  "Gibt es Konkurenz?",
  "Welche Warum-Frage kommt mir als erste in den Sinn?",
  "Weiß ich, wie ich vorgehen muss?",
  "Wissen meine Mitsteiter oder Kollegen genau, was zu tun ist?",
  "Bin ich unsicher?",
  "Wie unsicher bin ich?",
  "Bin ich sicher, dass ich das Richtige tue?",
  "Was verschafft mir Sicherheit, das Richtige zu tun?",
  "Habe ich bereits ein änhliches Problem gelöst?",
  "Wie bin ich in bisherigen Situationen vorgegangen?",
  "Habe ich Spaß an der Lösung?",
  "Habe ich Spaß an dem Problem?",
  "Bekomme ich an Anerkennung für meine Arbeit?",
  "Erkenne ich die Arbeit der anderen an?",
  "Wie perfekt soll die Lösung sein?",
  "Kann ich in meiner Umgebung klar denken?",
  "Was fehlt mir, um klar zu denken?",
  "Welche Fähigkeiten fehlen mir zu Lösung des Problems?",
  "Welches Wissen fehlt mir zur Lösung des Problems?",
  "Handelt es sich um ein Problem?",
  "Gibt es etwas, das wichtiger ist und ich zunächst erledigen sollte?",
  "Bin ich ein Feuerlöscher?",
  "Habe ich einen coolen Kopf?",
  "Weiß ich bei jedem Schritt bereits schon den nächsten Schritt?",
  "Kenne ich meinen Weg?",
  "Habe ich ein Ziel?",
  "Habe ich mein Problem schon einmal aufgeschrieben?",
  "Werde ich bei der Lösung des Problems etwas neues lernen?",
  "Muss ich noch etwas lernen, bevor ich das Problem lösen kann?",
  "Kenne ich die Definition der Begriffe genau, die ich verwende?",
  "Schafft meine Lösung mehr Freiheit für Menschen?",
  "Ist das, was ich tue aus meiner Sicht eher gut oder schlecht?",
  "Tue ich mir etwas Gutes, nachdem ich das Problem gelöst habe?",
  "Tut mir die Lösung des Problems gut?",
  "Wie schaffe ich es, dass ich das Problem gerne löse?",
  "Welche Eigenschaften fehlen mir zur Lösung des Problems?",
  "Welche Eigenschaften haben andere, die mir helfen könnten?",
  "Wie groß ist mein Einfluss auf das Problem?",
  "Bin ich ausreichend vernetzt um das Problem mit anderen zu lösen?",
  "Bekomme ich genügend Rückhalt aus meiner Umgebung?",
  "Gibt es Werkzeuge, die mir bei der Lösung des Problems helfen?",
  "Welche Werkzeuge helfen bei der Lösung meines Problems?",
  "Was möchte ich alles erreichen? Bin ich auf dem richtigen Weg?",
  "Stelle ich mir töglich eine neue Frage?",
  "Habe ich ein Motto des Tages?",
  "Mit welchem Gedanken wache ich morgens auf?",
  "Was inspiriert mich?"
]
